LOCAL_PATH := $(call my-dir)/..

include $(CLEAR_VARS)

LOCAL_SRC_FILES := sqlite3.c

LOCAL_MODULE := sqlcipher

LOCAL_CFLAGS := -DSQLITE_HAS_CODEC -DSQLITE_TEMP_STORE=2 -DSQLITE_THREADSAFE=1 -DSQLCIPHER_CRYPTO_OPENSSL
LOCAL_C_INCLUDES := $(OPENSSL_INCLUDE)
LOCAL_LDLIBS := -lcrypto1.1 -lssl1.1
LOCAL_LDFLAGS := -L$(OPENSSL_LIB)

include $(BUILD_SHARED_LIBRARY)
